# Generated by Django 5.2.4 on 2025-07-31 15:58

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_selected_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repo_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('user', 'repo_id')},
        ),
    ]
