# Generated by Django 5.2.4 on 2025-08-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_repository_repo_id_alter_user_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
